sudo: false
language: cpp

compiler:
  - gcc
  - clang

install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi

addons:
  apt:
    packages:
    - gcc-4.8
    - g++-4.8
    - clang
    - cmake
    - libeigen3-dev

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make
