sudo: false

language: cpp

os:
  - osx

compiler:
  - clang

before_install:
  - brew update
  - brew unlink cmake
  - brew install cmake

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make
