language: cpp

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

install:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
         wget http://www.cmake.org/files/v3.2/cmake-3.2.3-Linux-i386.tar.gz
      && tar -xzf cmake-3.2.3-Linux-i386.tar.gz
      && sudo ln -s cmake-3.2.3-Linux-i386/bin/cmake /usr/bin/cmake
      && sudo apt-add-repository -y ppa:ubuntu-toolchain-r/test
      && sudo apt-get -qq update
      && sudo apt-get -qq install g++-4.8
      && export CXX="g++-4.8"
      && export CC="gcc-4.8"
      ;
    else
         brew update
      && brew unlink cmake
      && brew install cmake
      ;
    fi

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make
