language: cpp

compiler:
  - gcc

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -qq update
  - sudo apt-get -qq install g++-4.8

addons:
  apt:
    packages:
    - cmake
    - libeigen3-dev

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make
