language: cpp

os:
  - linux

compiler:
  - gcc
  - clang

before_install:
  - wget http://www.cmake.org/files/v3.2/cmake-3.2.3-Linux-x86_64.tar.gz
  - tar -xzf cmake-3.2.3-Linux-x86_64.tar.gz
  - sudo apt-add-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-add-repository -y ppa:kubuntu-ppa/backports
  - sudo apt-get -qq update
  - sudo apt-get -qq install g++-4.8 libeigen3-dev
  - export CXX="g++-4.8"
  - export CC="gcc-4.8"

before_script:
  - mkdir build
  - cd build
  - ../cmake-3.2.3-Linux-x86_64/bin/cmake ..

script:
  - make
  - make test

after_success:
  - ctest -vv -D ExperimentalMemCheck
